name: Try

on: push

jobs:
  Requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Requirements.txt
      uses: ryan-rozario/pipreqs-action-cpy@master
      with:
        PROJECT_PATH: .
        REQUIREMENT_PATH: ./requirements.txt
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install Dependencies
      run: pip install --quiet --requirement requirements.txt
    - name: Lint Code
      uses: konstruktoid/action-pylint@v0.0.7
#       run: |
#         flake8 --ignore=E501,E231 *.py
#         pylint --disable=C0301 --disable=C0326 *.py
    - name: Unit tests
      run: python -m unittest --verbose --failfast
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#     - run: date
#   job2:
#     runs-on: windows-latest
#     steps:
#     - run: date
#   job3:
#     needs: [job1, job2]
#     runs-on: macos-latest
#     steps:
#     - run: date
